distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.9/apache-maven-3.9.9-bin.zip
distributionBase=.mvn/wrapper
distributionPath=apache-maven
zipStoreBase=.mvn/wrapper
zipStorePath=apache-maven
